### PR TITLE
New colors update.

### PR DESCRIPTION
**Pull request by lowercasedots**
Took your new colors from the Brackets extension update a few days ago and ported them over to Atom. (Plus a minor bracket matcher tweak.)

### CODE REVIEW

**Comment by taniarascia** [comment]
Excellent, thank you! Sorry I didn't get around to this sooner, was on vacation all weekend.

**Comment by lowercasedots** [comment]
No problem! Curiously, does updating the repo trigger the Atom package to update, or is there some sort of additional switch that needs to be thrown for that? I certainly don't mind including it in my pull requests - if it's something which can be done through here, anyway.

**Comment by taniarascia** [comment]
Yes, I was thinking about that. I believe I need to do it by adding a new tag and pushing to the atom repo or something. It's been like a year, and I annoyingly didn't make a tutorial about it, so now I have to try to remember again. Considering Atom is Github, I would it would automatically integrate.

**Comment by taniarascia** [comment]
Nevermind, I figured it out. It's just `apm publish major/minor/patch`.

**Pull request merged**
